#!/bin/bash

set -o nounset
set -o errexit

echo " *** rpi-update is not necessary under Compass Linux.  Do not use it. ***"
echo " *** To update your operating system, use                             ***"
echo " *** 'apt-get update && apt-get upgrade'                              ***"
